import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/provider";
import Header from "@/components/common/Header";
import NoteList from "@/components/common/NoteList";
import AddNoteForm from "@/components/common/AddNoteForm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dynamic Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReduxProvider>
          <div className="max-w-4xl mx-auto mt-4">
            <Header />
            <div className="flex gap-2 w-full">
              <div className="w-2/3">{children}</div>
              <NoteList />
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
